name: CI&CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci.yml
    steps:
      - uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose -f $COMPOSE_FILE build --pull

      - name: Up docker container
        run: docker-compose -f $COMPOSE_FILE up -d

      - name: Validate composer.json and composer.lock
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer validate --strict

      - name: Install dependencies
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer install

      - name: Run test suite
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer run-script test

      - name: Upload coverage results to Coveralls
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer run-script php-coveralls

      - name: Run code analyse
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer run-script analyse

      - name: Run code style check
        run: docker-compose -f $COMPOSE_FILE exec -T php-cli composer run-script code-style

      - name: Finish step
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Packagist Sync
        uses: hotaruma/packagist-sync@v1.0.0
        with:
          api-token: ${{ secrets.packagist_token }}
